## Spring application
#spring.application.name=api-gateway
#
## Spring Cloud Gateway routes
#spring.cloud.gateway.routes[0].id=inventory-service
#spring.cloud.gateway.routes[0].uri=lb://inventory-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/inventory/**
#
#spring.cloud.gateway.routes[1].id=order-service
#spring.cloud.gateway.routes[1].uri=lb://order-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**
#
## Eureka client
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## Server
#server.port=8081
#
#
