INSERT INTO product (name, price, quantity) VALUES
                                                ('Laptop Pro 15"', 1200.00, 10),
                                                ('Wireless Mouse', 25.50, 50),
                                                ('Mechanical Keyboard', 85.00, 30),
                                                ('Gaming Monitor 27"', 300.00, 15),
                                                ('USB-C Hub', 45.00, 40),
                                                ('External SSD 1TB', 150.00, 20),
                                                ('Smartphone X', 999.99, 25),
                                                ('Bluetooth Headphones', 120.00, 35),
                                                ('Smartwatch Series 5', 250.00, 18),
                                                ('Portable Charger 20000mAh', 60.00, 45),
                                                ('HD Webcam', 75.00, 22),
                                                ('Ergonomic Chair', 180.00, 12),
                                                ('Office Desk', 220.00, 8),
                                                ('4K TV 55"', 700.00, 10),
                                                ('Soundbar System', 350.00, 14),
                                                ('Wireless Router AX6000', 280.00, 16),
                                                ('Drone Camera', 500.00, 6),
                                                ('Action Camera 4K', 320.00, 20),
                                                ('Smart Home Speaker', 130.00, 28),
                                                ('Fitness Tracker', 90.00, 33);
